{% extends "secondary.phtml" %}
{% block title %}{{block.super}}: Thanks for the note!{% endblock %}
{% block body_attributes %}id="secondary"{% endblock %}
{% block meta_description %} Thank you for contacting us, we'll get back to you as soon as we can.{% endblock %}

{% block secondary_content %}
		<h2><strong>Thanks!</strong></h2>
		<p>Thanks for sending us a message. We'll get back to you as soon as we can.</p>
{% endblock %}