<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.1//EN"
		"http://www.w3.org/TR/xhtml11/DTD/xhtml11.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>{% load compressed %}
	<title>{% block title %}Match Strike{% endblock %}</title>
	<meta http-equiv="content-type" content="text/html; charset=utf-8" />
	{% block links %}{% compressed_css 'main' %}
	<!--[if lte IE 7]>{% compressed_css 'ie7' %}<![endif]-->
	<!--[if lt IE 7]>{% compressed_css 'ie6' %}<![endif]-->
	<link rel="icon" href="{{MEDIA_URL}}img/favicon.ico" type="image/x-icon" />
	<link rel="alternate" type="application/rss+xml" title="Match Strike's Blog Feed" href="http://matchstrike.net/strikepad/feed/" />{% endblock %}
	{% block scripts %}{% compressed_js 'main' %}
	<!--[if lte IE 7]>{% compressed_js 'ie7' %}</script><![endif]-->
	<!--[if lt IE 7]>{% compressed_js 'ie6' %}<![endif]-->{% endblock %}
	<meta name="ROBOTS" content="{% block meta_robots %}ALL{% endblock %}" />
	<meta name="Description" content="{% block meta_description %}Match Strike is a development firm based in Orlando, Florida.{% endblock %}" />
	<meta name="author" content="{% block meta_author %}Match Strike{% endblock %}" />
	<meta name="Copyright" content="{% block meta_copyright %}Copyright 2002 - 2009 Match Strike. All Rights Reserved.{% endblock %}" />
</head>
<body {% block body_attributes %}{% endblock %}>
	<h1><a href="{% url index%}">{% block heading %}Match Strike{% endblock %}</a></h1>
	<ul id="navigation">
		<li><a href="{% url pricing %}">pricing</a></li>
		<li><a href="{% url work %}">work</a></li>
		<li><a href="{% url contact_us %}">contact</a></li>
		<li><a href="/strikepad/">blog</a></li>
	</ul>
	<div id="primary_content">
		{% block content %}{% endblock %}
	</div>
	<div id="related_content">
		<h2>Our latest projects and notes</h2>
			{% include 'recent_events.phtml' %}
	</div>
	<ul id="footer">
		<li class="first">&copy; <a href="/">Match Strike</a> LLC.</li>
		<li>Orlando, Florida</li>
		<li>Call us: (407) 588 - 7483</li>
		<li>Follow us on <a href="http://twitter.com/matchstrike/">Twitter</a>.</li>
	</ul>
</body>
</html>

