{% extends "secondary.phtml" %}
{% block title %}{{block.super}}: Hire us{% endblock %}
{% block body_attributes %}id="secondary"{% endblock %}
{% block meta_description %}Match Strike builds websites in one week sprints. Our base sprint billing rate is $8,000 per three-man development team per week.{% endblock %}

{% block secondary_content %}
			<h2>A <strong>Sprint</strong> to victory</h2>
			<p>We build websites in <strong>sprints</strong>. A sprint is a one-week period of time where a team of three highly skilled programmers focuses only on your site or application, producing amazing results.</p>

			<p>A single week may not seem like much, but with the right team, a week can change the world. This site, including our <a href="/strikepad/">blog</a>, could be built in a sprint. <a href="http://atlibs.matchstrike.net/">Atlibs</a> could be built in a sprint. A larger site like <a href="http://presskitn.com/">Presskit’n</a> could be built in a handful of sprints. If you <a href="/contact_us/">contact us</a>, we’d be happy to listen to your requirements and determine what we can build for you in a single sprint or more.</p>

			<p>Our base billing rate is $8,000 per three-man development team per week, or $6,000 per two-man development team per week. We offer a discount for clients who book sprints back-to-back. </p>
			
			<h2>Built on a <strong>Daily</strong> basis</h2>
			
			<p>For smaller projects, we offer the Daily. A daily is like a sprint, but only lasts one day, only has two developers, and costs much less at $1,450.</p>
			
			<p>One of our own projects, the <a href="http://happo.matchstrike.net/">HAPPO web app</a>, was built in a day. We suggest scheduling dailies a few days apart, to give you some time to give feedback on the development of the project. Most simple business presence sites can be built in a daily or two.</p>
			
			<p>We also offer maintenance plans for sites of all sizes.</p>
{% endblock %}