{% extends "secondary.phtml" %}
{% block title %}{{block.super}}: Send clients our way.{% endblock %}
{% block body_attributes %}id="secondary"{% endblock %}
{% block meta_description %}If you know of an individual or business that could use our services, send them our way. If we gain a new client from it, you'll earn a finder's fee of 10% of our sprint price.{% endblock %}

{% block secondary_content %}
		<h2><strong>Refer us</strong> and earn</h2>
		<p>
			If you know of an individual or business that could use our services, send them our way. If we gain a new client from it, you'll earn a finder's fee of 10% of our sprint price.
		</p>
		<p>
			There are a <strong>few rules</strong>, of course. First, this offer only applies to sprints, not maintenance contracts or other smaller contracts. You also can't be affiliated with (or employed by) the company you connect us with.
		</p>
		<p>
			You also have to disclose the referral process if you're recommending us through this offer. We stand by our work as the primary motivator of our client relationships; this offer is only an incentive to develop new connections. If you know someone who needs high quality web development work, <a href="mailto:info@matchstrike.net">send us an e-mail</a> about it and then have them give us a call.
		</p>
{% endblock %}