{% extends "base.phtml" %}
{% block title %}{{block.super}}: The work{% endblock %}
{% block body_attributes %}id="secondary"{% endblock %}
{% block meta_description %}Match Strike project portfolio: Featuring HootCourse, At Libs, HAPPO and Product Place Me.{% endblock %}

{% block content %}
			<div class="show_container">
				<div class="hootcourse workshow">
					<div class="hootcourse_main workslide">
						<a class="featurelink hootcourse1" href="http://hootcourse.com" target="_blank">HootCourse</a>
						<h3>HootCourse</h3>
						<p>A HootCourse is a virtual classroom where teachers can sync social networking and blogging to their real-life courses in real-time.</p>
					</div>
					<div class="hootcourse_dashboard workslide">
						<a class="featurelink hootcourse2" href="http://hootcourse.com" target="_blank">HootCourse</a>
						<h3>Course Page</h3>
						<p>A HootCourse shows tweets and Facebook status updates of all students in the course, given that the course hashtag is included. Blog posts can be written directly in the HootCourse interface, seamlessly integratin with multiple blog platforms.</p>
					</div>
					<div class="hootcourse_create workslide">
						<a class="featurelink hootcourse3" href="http://hootcourse.com" target="_blank">HootCourse</a>
						<h3>Mini-Client</h3>
						<p>The HootCourse mini-client can be embedded anywhere, allowing teachers to easily host their class discussions in popular learning systems, Google Sies, and more. The format also works great for mobile.</p>
					</div>
				</div>
				<ul id="hootcourse_nav" class="show_nav">
					<li><a class="hootcourse_thumb1 thumb" href="#">Atlibs Main</a></li>
					<li><a class="hootcourse_thumb2 thumb" href="#">Atlibs Login</a></li>
					<li><a class="hootcourse_thumb3 thumb" href="#">Atlibs Create</a></li>
				</ul>
			</div>


			<div class="show_container">
				<div class="atlibs workshow">
					<div class="atlibs_main workslide">
						<a class="featurelink atlibs1" href="http://atlibs.matchstrike.net" target="_blank">Visit website</a>
						<h3>At Libs</h3>
						<p>A fun, craft-project-themed look goes with this Twitter-based game, where users can fill out or create At Libs, a 140-character spin on Mad Libs.</p>
					</div>
					<div class="atlibs_login workslide">
						<a class="featurelink atlibs2" href="http://atlibs.matchstrike.net" target="_blank">Visit website</a>
						<h3>Twitter/Facebook</h3>
						<p>At Libs is built with Twitter and Facebook users in mind, allowing either to log in and play the game. At Libs can be linked directly, and Twitter users can include their friends' Twitter handles directly in their At Libs.</p>
					</div>
					<div class="atlibs_create workslide">
						<a class="featurelink atlibs3" href="http://atlibs.matchstrike.net" target="_blank">Visit website</a>
						<h3>Make your own</h3>
						<p>The create interface is simplified, with the system handling all character counts in real-time. Examples are provided to help players make the most of the game. Featured At Libs are approved though a backend interface.</p>
					</div>
				</div>
				<ul id="atlibs_nav" class="show_nav">
					<li><a class="atlibs_thumb1 thumb" href="#">Atlibs Main</a></li>
					<li><a class="atlibs_thumb2 thumb" href="#">Atlibs Login</a></li>
					<li><a class="atlibs_thumb3 thumb" href="#">Atlibs Create</a></li>
				</ul>
			</div>
			
			<div class="show_container">
				<div class="happo workshow">
					<div class="happo_main workslide">
						<a class="featurelink happo1" href="http://happo.matchstrike.net" target="_blank">HAPPO</a>
						<h3>HAPPO</h3>
						<p>HAPPO is a popular Twitter hashtag which helps PR pros find jobs. We took a day to make a tool that helped PR pros look for HAPPO posts just for their city.</p>
					</div>
					<div class="happo_login workslide">
						<a class="featurelink happo2" href="http://happo.matchstrike.net" target="_blank">HAPPO</a>
						<h3>City Listing</h3>
						<p>City pages list all posts by that city's HAPPO champs. HAPPO champs are the ones in charge of running HAPPO for their city. Additionally, a city-specific hashtag search is shown, letting a user get all the HAPPO tweets for that city.</p>
					</div>
					<div class="happo_create workslide">
						<a class="featurelink happo3" href="http://happo.matchstrike.net" target="_blank">HAPPO</a>
						<h3>Powerful Backend</h3>
						<p>HAPPO admins can log in to an easy-to-use backend, editing HAPPO champs, adding cities or making corrections.</p>
					</div>
				</div>
				<ul id="happo_nav" class="show_nav">
					<li><a class="happo_thumb1 thumb" href="#">Atlibs Main</a></li>
					<li><a class="happo_thumb2 thumb" href="#">Atlibs Login</a></li>
					<li><a class="happo_thumb3 thumb" href="#">Atlibs Create</a></li>
				</ul>
			</div>
			<div class="show_container">
				<div class="ppm workshow">
					<div class="ppm_main workslide">
						<a class="featurelink ppm1" href="http://productplaceme.com" target="_blank">Product place me - Product placement</a>
						<h3>Product Place Me</h3>
						<p>Product Place Me connects filmmakers and other creative types with advertisers for product placement opportunities.</p>
					</div>
					<div class="ppm_placement workslide">
						<a class="featurelink ppm2" href="http://productplaceme.com" target="_blank">Product place me - Product placement</a>
						<h3>Submit Placement</h3>
						<p>The Submit form is straightforward and integrates directly with Mailchimp for easy setup.</p>
					</div>
					<div class="ppm_backend workslide">
						<a class="featurelink ppm3" href="http://productplaceme.com" target="_blank">Product place me - Product placement</a>
						<h3>Backend</h3>
						<p>For more lightweight projects, we'll often go with Wordpress for the underlying site architecture. Django has raw power, but for certain projects such as blogs, Wordpress gets the job done.</p>
					</div>
				</div>
				<ul id="ppm_nav" class="show_nav">
					<li><a class="ppm_thumb1 thumb" href="#">PPM main</a></li>
					<li><a class="ppm_thumb2 thumb" href="#">PPM Submit</a></li>
					<li><a class="ppm_thumb3 thumb" href="#">PPM backend</a></li>
				</ul>
			</div>

{% endblock %}